### ISSUE TITLE
Use expand in Samen Meten API

### ISSUE THREAD

**Issue by elma13** [rivm-syso/samanapir#2]
The Samen Meten API can have an expand argument to get more data in one call. We will use this to obtain the meta-data for the sensors.

**Comment by elma13** [comment]
@jspijker , Can you check if the new function to extract data from the samen meten API works for you and can be used for the new version of the Analyse Tool?

**Comment by jspijker** [comment]
Some API calls return an error, for example:

```
v1<-GetSamenMetenAPIobs("24383", "SSK_LH003", 20220201, 20220215)
```

**Comment by elma13** [comment]
> v1<-GetSamenMetenAPIobs("24383", "SSK_LH003", 20220201, 20220215)

@jspijker , that is correct, there is no data for this sensor and datastream (pm10_kal) in this period. If the result is empty, then an error is raised.
